[main]
font=JetBrainsMono Nerd Font:size=13:weight=Medium
#font=FiraCode Nerd Font:size=13:weight=Medium
#font=GeistMono Nerd Font:size=13:weight=Medium
pad=10x10
dpi-aware=false
letter-spacing=0.5
font-size-adjustment=0.5

#include=~/.config/foot/themes/nvim-dark.ini
include=~/.config/foot/themes/less-dark.ini
include=~/.config/foot/themes/nvim-light.ini

[key-bindings]
# Set a single key combination to toggle back and forth between light and dark
color-theme-toggle=Control+Shift+t
