[main]
#font=JetBrainsMono Nerd Font:pixelsize=22:weight=Medium
#font=FiraCode Nerd Font:size=13:weight=Medium
#font=GeistMono Nerd Font:size=13:weight=Medium
font=JetBrainsMono Nerd Font:pixelsize=22
font-bold=JetBrainsMono Nerd Font:pixelsize=22:style=Bold
font-italic=JetBrainsMono Nerd Font:pixelsize=22:style=Italic
font-bold-italic=JetBrainsMono Nerd Font:pixelsize=22:style=Bold Italic

pad=20x16
dpi-aware=true
letter-spacing=0.5
font-size-adjustment=2.0px

#include=~/.config/foot/themes/nvim-dark.ini
include=~/.config/foot/themes/less-dark.ini
include=~/.config/foot/themes/nvim-light.ini

[key-bindings]
# Set a single key combination to toggle back and forth between light and dark
color-theme-toggle=Control+Shift+t

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes
