PATH=$PATH:$HOME/.local/bin:$HOME/.local/share/bob/nvim-bin:$HOME/go/bin
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
EDITOR=/home/niri/.local/share/bob/nvim-bin/nvim
GDK_BACKEND=wayland
QT_QPA_PLATFORM=wayland
XFT_ANTIALIAS "1"
XFT_HINTING "1"
XFT_HINTSTYLE "hintslight"
XFT_RGBA "rgb"
