outputs = "All"
position = "Top"
enable_esc_key = true

[appearance]
font = "JetBrainsMono Nerd Font"
text_color = "#7E817C"
scale_factor = 1.5
workspace_colors = [ "#343940", "#4B6968", "#385251" ]

[appearance.warning_color]
base = "#857960"
strong = "#93866A"

[appearance.danger_color]
base = "#865F60"
strong = "#987071"

[appearance.background_color]
base = "#111317"
strong = "#30353A"
weak = "#22272B"

[modules]
left = [ [ "ClusterContext", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Tempo", "Settings", "CustomNotifications"] ]

[tempo]
clock_format = "%a %d %b %R"
weather_location = { City = "Bergen" }
weather_indicator = "Icon"

[settings]
shutdown_cmd = "graceful-shutdown.sh"
reboot_cmd = "graceful-reboot.sh"


[[CustomModule]]
name = "ClusterContext"
type = "Button"
icon = "󱃾"
listen_cmd = '''
while true; do
  "$HOME/.local/bin/ctx.sh" | jq -Rsc '{ text: rtrimstr("\n"), alt: "" }'
  sleep 5
done
'''

[[CustomModule]]
name = "CustomNotifications"
type = "Button"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"
