[colors-dark]
# Normal/bright palette that Neovim expects
foreground=dcdccc
background=14161b
regular0=1f1f1f   ; black
regular1=cc9393   ; red
regular2=7f9f7f   ; green
regular3=d0bf8f   ; yellow
regular4=6fa0af   ; blue
regular5=cc85cc   ; magenta
regular6=8cd0d3   ; cyan
regular7=efefef   ; white

bright0=606060    ; bright black
bright1=dca3a3    ; bright red
bright2=bfebbf    ; bright green
bright3=f0dfaf    ; bright yellow
bright4=8cd0d3    ; bright blue
bright5=cc85cc    ; bright magenta
bright6=8cd0d3    ; bright cyan
bright7=ffffff    ; bright white

