[preferred]
# Use the GTK portal for general things like file pickers
default=gnome;gtk

# Use the GNOME portal strictly for screencasting/sharing
#org.freedesktop.impl.portal.ScreenCast=gnome
#org.freedesktop.impl.portal.Screenshot=gnome
