[preferred]
# Use GTK for standard elements like file choosers and app pickers
default=gtk

# Force Niri to use GNOME specifically for screen sharing and screenshots
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome

